### ISSUE TITLE
安装完成后启动不了  journalctl -u mysqld错误提示如下

### ISSUE THREAD

**Issue by xueyangkk** [2233466866/lnmp#4]
Jul 06 13:46:41 cc69211b475e systemd[1]: Starting MySQL Server...
Jul 06 13:47:45 cc69211b475e systemd[1]: mysqld.service: control process exited, code=exited status=1
Jul 06 13:47:45 cc69211b475e systemd[1]: Failed to start MySQL Server.
Jul 06 13:47:45 cc69211b475e systemd[1]: Unit mysqld.service entered failed state.
Jul 06 13:47:45 cc69211b475e systemd[1]: mysqld.service failed.
Jul 06 13:47:46 cc69211b475e systemd[1]: mysqld.service holdoff time over, scheduling restart.
Jul 06 13:47:46 cc69211b475e systemd[1]: Stopped MySQL Server.
Jul 06 13:47:46 cc69211b475e systemd[1]: Starting MySQL Server...
Jul 06 13:47:47 cc69211b475e mysqld[157]: Unable to determine if daemon is running: No such file or directory
Jul 06 13:47:47 cc69211b475e systemd[1]: mysqld.service: control process exited, code=exited status=1
Jul 06 13:47:47 cc69211b475e systemd[1]: Failed to start MySQL Server.
Jul 06 13:47:47 cc69211b475e systemd[1]: Unit mysqld.service entered failed state.
Jul 06 13:47:47 cc69211b475e systemd[1]: mysqld.service failed.
Jul 06 13:47:47 cc69211b475e systemd[1]: mysqld.service holdoff time over, scheduling restart.
Jul 06 13:47:47 cc69211b475e systemd[1]: Stopped MySQL Server.
Jul 06 13:47:47 cc69211b475e systemd[1]: Starting MySQL Server...
Jul 06 13:47:48 cc69211b475e mysqld[180]: Unable to determine if daemon is running: No such file or directory
Jul 06 13:47:48 cc69211b475e systemd[1]: mysqld.service: control process exited, code=exited status=1

**Comment by hao1305430263** [comment]
同样遇到上面错误，求解决

**Comment by 2233466866** [comment]
请正确配置/etc/my.conf

**Comment by 2233466866** [comment]
> 同样遇到上面错误，求解决

请正确配置/etc/my.conf

**Comment by 2233466866** [comment]
> Jul 06 13:46:41 cc69211b475e systemd[1]: Starting MySQL Server...
> Jul 06 13:47:45 cc69211b475e systemd[1]: mysqld.service: control process exited, code=exited status=1
> Jul 06 13:47:45 cc69211b475e systemd[1]: Failed to start MySQL Server.
> Jul 06 13:47:45 cc69211b475e systemd[1]: Unit mysqld.service entered failed state.
> Jul 06 13:47:45 cc69211b475e systemd[1]: mysqld.service failed.
> Jul 06 13:47:46 cc69211b475e systemd[1]: mysqld.service holdoff time over, scheduling restart.
> Jul 06 13:47:46 cc69211b475e systemd[1]: Stopped MySQL Server.
> Jul 06 13:47:46 cc69211b475e systemd[1]: Starting MySQL Server...
> Jul 06 13:47:47 cc69211b475e mysqld[157]: Unable to determine if daemon is running: No such file or directory
> Jul 06 13:47:47 cc69211b475e systemd[1]: mysqld.service: control process exited, code=exited status=1
> Jul 06 13:47:47 cc69211b475e systemd[1]: Failed to start MySQL Server.
> Jul 06 13:47:47 cc69211b475e systemd[1]: Unit mysqld.service entered failed state.
> Jul 06 13:47:47 cc69211b475e systemd[1]: mysqld.service failed.
> Jul 06 13:47:47 cc69211b475e systemd[1]: mysqld.service holdoff time over, scheduling restart.
> Jul 06 13:47:47 cc69211b475e systemd[1]: Stopped MySQL Server.
> Jul 06 13:47:47 cc69211b475e systemd[1]: Starting MySQL Server...
> Jul 06 13:47:48 cc69211b475e mysqld[180]: Unable to determine if daemon is running: No such file or directory
> Jul 06 13:47:48 cc69211b475e systemd[1]: mysqld.service: control process exited, code=exited status=1

请正确配置/etc/my.conf

**Comment by 2233466866** [comment]
# 解决方案
1. 请正确配置/etc/my.cnf
1. docker run 增加 --privileged=true
