### ISSUE TITLE
Failed to get D-Bus connection: No such file or directory

### ISSUE THREAD

**Issue by gaoming110** [2233466866/lnmp#8]
Failed to get D-Bus connection: No such file or directory

**Comment by dahua997** [comment]
me too

**Comment by yingxj** [comment]
找了很久，这文章说得比较清楚
https://zhuanlan.zhihu.com/p/473252130

**Comment by 2233466866** [comment]
> 找了很久，这文章说得比较清楚 https://zhuanlan.zhihu.com/p/473252130

感谢科普，将依据此方案提交一个测试版本，是否提交正式版将视测试结果而定。

**Comment by 2233466866** [comment]
已为此方案设计上传了1.14版，欢迎使用。
